sudo: required
services: 
        - docker

before_install:
        - docker build -t histeh -t hiteshi/docker-react -f Dockerfile.dev .


script:
        - docker run -e CI=true hiteshi/docker-react  npm run test -- --coverage        
language: generic 
